var debug = require('debug')

exports.handlers = debug('wc:handlers')
exports.errors = debug('wc:errors')
exports.authentication = debug('wc:authentication')
exports.server = debug('wc:server')
exports.balance = debug('wc:balance')
exports.home = debug('wc:home')
exports.insert = debug('wc:insert')
exports.ledger = debug('wc:ledger')
exports.today = debug('wc:today')
exports.tx = debug('wc:tx')
